# Generated by Django 5.2.8 on 2026-03-22 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img_src', models.URLField(blank=True, null=True)),
                ('years_of_age', models.CharField(max_length=9)),
                ('bio', models.TextField()),
                ('works', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'author',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img_src', models.URLField(blank=True, null=True)),
                ('publication_date', models.DateField()),
                ('short_desc', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author')),
            ],
            options={
                'db_table': 'book',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='books.book')),
            ],
            options={
                'db_table': 'book_detail',
            },
        ),
    ]
